//Unit en charge de l'affichage des ascii-arts.
unit unitASCII;
{$codepage utf8}
{$mode objfpc}{$H+}

interface
//----- FONCTIONS ET PROCEDURES -----
//Affiche le logo pour le menu principal
procedure afficherLogo();  
//Affiche le titre du menu principal
procedure afficherTitreMenuPrincipal();
//Dessine le logo du repos
procedure afficherSleep();













implementation
uses
    GestionEcran;

 
//----- FONCTIONS ET PROCEDURES -----
//affiche un pixel de couleur color à la position du curseur
procedure dessinerPixel(color:integer);
var
  i:integer;
begin
  couleurFond(color);
  write('  ');
end;

//affiche une chaine de caractères en l'interprétant comme une succession de pixels colorés
procedure dessinerLignePixel(ligne : string);
const
   colBleu = DarkGray;
   colMarron = LightGray;
   colNoir = Black;
   colBeige = Brown;
   colFond = Black;
   colRouge = LightRed;
   colTexte = White;
var
  i:integer;
begin
  for i:= 1 to Length(ligne) do
      case ligne[i] of
           'W',' ':dessinerPixel(colFond);
           'B':dessinerPixel(colBleu);
           'R':dessinerPixel(colRouge);
           'N':dessinerPixel(colNoir);
           'M':dessinerPixel(colMarron);
           'Y':dessinerPixel(colBeige);
           'T':dessinerPixel(colTexte);
      end;
  writeln;
end;

//Affiche le titre du menu principal
procedure afficherTitreMenuPrincipal();
begin

  deplacerCurseurXY(16,7);dessinerLignePixel('WWWWWWWWWTWWWTWWTTTWWTWWWTWWTTTTWTTTTTWTTTTTWTTTTW');
  deplacerCurseurXY(16,8);dessinerLignePixel('WWWWWWWWWTTWTTWTWWWTWTTWWTWTWWWWWWWTWWWTWWWWWTWWWT');
  deplacerCurseurXY(16,9);dessinerLignePixel('WWWWWWWWWTWTWTWTWWWTWTTTWTWTWWWWWWWTWWWTWWWWWTWWWT');
  deplacerCurseurXY(16,10);dessinerLignePixel('WWWWWWWWWTWWWTWTWWWTWTWTTTWWTTTWWWWTWWWTTTWWWTTTTW');
  deplacerCurseurXY(16,11);dessinerLignePixel('WWWWWWWWWTWWWTWTWWWTWTWWTTWWWWWTWWWTWWWTWWWWWTTTWW');
  deplacerCurseurXY(16,12);dessinerLignePixel('WWWWWWWWWTWWWTWTWWWTWTWWWTWWWWWTWWWTWWWTWWWWWTWTTW');
  deplacerCurseurXY(16,13);dessinerLignePixel('WWWWWWWWWTWWWTWWTTTWWTWWWTWTTTTWWWWTWWWTTTTTWTWWTT');
  deplacerCurseurXY(16,14);dessinerLignePixel('WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW');
  deplacerCurseurXY(16,15);dessinerLignePixel('WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW');
  deplacerCurseurXY(16,16);dessinerLignePixel('WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW');
  deplacerCurseurXY(16,17);dessinerLignePixel('WWWWWWWWWWWWTWWWTWTWWWTWTWWWTWTTTTTWTTTTTWTTTTWWWW');
  deplacerCurseurXY(16,18);dessinerLignePixel('WWWWWWWWWWWWTWWWTWTWWWTWTTWWTWWWTWWWTWWWWWTWWWTWWW');
  deplacerCurseurXY(16,19);dessinerLignePixel('WWWWWWWWWWWWTWWWTWTWWWTWTTTWTWWWTWWWTWWWWWTWWWTWWW');
  deplacerCurseurXY(16,20);dessinerLignePixel('WWWWWWWWWWWWTTTTTWTWWWTWTWTTTWWWTWWWTTTWWWTTTTWWWW');
  deplacerCurseurXY(16,21);dessinerLignePixel('WWWWWWWWWWWWTWWWTWTWWWTWTWWTTWWWTWWWTWWWWWTTTWWWWW');
  deplacerCurseurXY(16,22);dessinerLignePixel('WWWWWWWWWWWWTWWWTWTWWWTWTWWWTWWWTWWWTWWWWWTWTTWWWW');
  deplacerCurseurXY(16,23);dessinerLignePixel('WWWWWWWWWWWWTWWWTWWTTTWWTWWWTWWWTWWWTTTTTWTWWTTWWW');
end;

//Affiche le logo du jeu
procedure afficherLogo();
begin
  //On redimensionne la console
  changerTailleConsole(200,40);
  effacerEcran();
  writeln;  
  writeln;
  dessinerLignePixel('WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW');
  dessinerLignePixel('WWWWWWWWWWWWWWWWWWWWWWBBWWMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW');
  dessinerLignePixel('WWWWWWWWWWWWWWWWWWWWBBBWWMMBWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW');
  dessinerLignePixel('WWWWWWWWWWWWWWWWWWWBBBWMMMBBBMWWWMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW');
  dessinerLignePixel('WWWWWWWWWWWWWBBBBBBBBMMMMBBBBBWMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW');
  dessinerLignePixel('WWWWWWBBBBBBBBBBNNBBBBBBBBNNBBBBMMWWMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW');
  dessinerLignePixel('WWWWYYBBBBBBBNNRBBBBBBBBBBNNBBBBBMWMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW');
  dessinerLignePixel('WWWWYYYYYYBBBBBBYYYYYYYBBBBBBBBBBBMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW');
  dessinerLignePixel('WWWWYYWYYWYYWYYWYYWWWYYBBBYYYBBNNBBMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW');
  dessinerLignePixel('WWWWWWWWWWWWWWWWYYYYWYYYYYYYYYBNNBBBWWWWWWWWWWWWWWTWWWTWWTTTWWTWWWTWWTTTTWTTTTTWTTTTTWTTTTW');
  dessinerLignePixel('WWWWWWWWYYWYWWYWWYYWYYYYYYWWWYYYBBBBBWWWWWWWWWWWWWTTWTTWTWWWTWTTWWTWTWWWWWWWTWWWTWWWWWTWWWT');
  dessinerLignePixel('WWWWWYYWYYWYYWYWWWWYYWWWWWWWWWYYYBBBBWWWWWWWWWWWWWTWTWTWTWWWTWTTTWTWTWWWWWWWTWWWTWWWWWTWWWT');
  dessinerLignePixel('WWWWWWYYYYYYYYYYYYYYWWWWWWWWWWWYYBBNNWWWWWWWWWWWWWTWWWTWTWWWTWTWTTTWWTTTWWWWTWWWTTTWWWTTTTW');
  dessinerLignePixel('WWWWWWWYYYWWWWWWWWWWWWWWWWWWWWWYBBBNNWWWWWWWWWWWWWTWWWTWTWWWTWTWWTTWWWWWTWWWTWWWTWWWWWTTTWW');
  dessinerLignePixel('WWWWWWWWWWWBBBBBBBBBBBBBBBBBBBBBBBBBBWWWWWWWWWWWWWTWWWTWTWWWTWTWWWTWWWWWTWWWTWWWTWWWWWTWTTW');
  dessinerLignePixel('WWWWWWWWWBBBBBBBBBBBBBBBBBBBBBBBBBBBBWWWWWWWWWWWWWTWWWTWWTTTWWTWWWTWTTTTWWWWTWWWTTTTTWTWWTT');
  dessinerLignePixel('WWWWWWWWBBBBBBNNBBBBNNBBBBNNBBBBNNBBYWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW');
  dessinerLignePixel('WWWWWWWBBBBBBBNNBBBBNNBBBBNNBBBBNNBYWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW');
  dessinerLignePixel('WWWWWWWBBBBBBBYYYYYYYYYYYYYYYYYYYYYWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW');
  dessinerLignePixel('WWWWWWWBBBNNBYYWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWTWWWTWTWWWTWTWWWTWTTTTTWTTTTTWTTTTWWWW');
  dessinerLignePixel('WWWWWWWBBBNNYYWWWBBNNBBBBBNNBBBBBBBWWWWWWWWWWWWWWWWWWTWWWTWTWWWTWTTWWTWWWTWWWTWWWWWTWWWTWWW');
  dessinerLignePixel('WWWWWWWBBBBBYWWWBBBNYYYYYYYYYBBBBBBBWWWWWWWWWWWWWWWWWTWWWTWTWWWTWTTTWTWWWTWWWTWWWWWTWWWTWWW');
  dessinerLignePixel('WWWWWWWBBBBBYWWBBBBYYYWWWWWWYYBBNNBBBWWWWWWWWWWWWWWWWTTTTTWTWWWTWTWTTTWWWTWWWTTTWWWTTTTWWWW');
  dessinerLignePixel('WWWWWWWBBBBBYWWBBBBYWWWBBBBWWYBBNNBBBBWWWWWWWWWWWWWWWTWWWTWTWWWTWTWWTTWWWTWWWTWWWWWTTTWWWWW');
  dessinerLignePixel('WWWWWWWBBBBBYWWWBBBBBBBBBNNBWYBBBYYYBBWWWWWWWWWWWWWWWTWWWTWTWWWTWTWWWTWWWTWWWTWWWWWTWTTWWWW');
  dessinerLignePixel('WWWWWWWBBBNNYYWWWBNNBBBBBNNWWYBBYYYYYBWWWWWWWWWWWWWWWTWWWTWWTTTWWTWWWTWWWTWWWTTTTTWTWWTTWWW');
  dessinerLignePixel('WWWWWWWBBBNNBYYWWWWWWWWWWWWWYYBBYBBBYBWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW');
  dessinerLignePixel('WWWWWWWBBBBBBBYYYYYYYYYYYYYYYBBBYBYBYBWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW');
  dessinerLignePixel('WWWWWWWBBBBBWBBBBWBBBNNBBBBNNBBBYYYBYBWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW');
  dessinerLignePixel('WWWWWWWWBBBWBBBBWBBBBNNBBBBNNBBBBYYBYWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW');
  dessinerLignePixel('WWWWWWWWWBWBBBBWBBBBBBBBBBBBBBBBBBBYWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW');
  dessinerLignePixel('WWWWWWWWWWBBBBWWWWWWWWWWWWWWWWWBBBBYWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW');
  dessinerLignePixel('WWWWWWWWWBBBBBBBMMMMWWWWWWWWWWBBBBYYWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW');
  dessinerLignePixel('WWWWWWWWBBBBBBBBWWWWWWWWWMMWMMBBBYYYWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW');
  dessinerLignePixel('WWWWWWWWBYYYYYYYMMMMWWWWMMWMMMYYYYYYWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW');
end;

//Dessine le logo du repos
procedure afficherSleep();
begin
     deplacerCurseurXY(50,5); dessinerLignePixel('TTTTTTTTTTT');
     deplacerCurseurXY(50,6); dessinerLignePixel('         T ');
     deplacerCurseurXY(50,7); dessinerLignePixel('        T  ');
     deplacerCurseurXY(50,8); dessinerLignePixel('       T   ');
     deplacerCurseurXY(50,9);dessinerLignePixel('      T    ');
     deplacerCurseurXY(50,10);dessinerLignePixel('     T     ');
     deplacerCurseurXY(50,11);dessinerLignePixel('    T              TTTTTTTTT');
     deplacerCurseurXY(50,12);dessinerLignePixel('   T                      T ');
     deplacerCurseurXY(50,13);dessinerLignePixel('  T                      T  ');
     deplacerCurseurXY(50,14);dessinerLignePixel(' T                      T   ');
     deplacerCurseurXY(50,15);dessinerLignePixel('TTTTTTTTTT             T    ');
     deplacerCurseurXY(50,16);dessinerLignePixel('                      T     ');
     deplacerCurseurXY(50,17);dessinerLignePixel('                     T      ');
     deplacerCurseurXY(50,18);dessinerLignePixel('                    T       ');
     deplacerCurseurXY(50,19);dessinerLignePixel('                   TTTTTTTTT');

     deplacerCurseurXY(50,21);dessinerLignePixel('        TTTTTTT');
     deplacerCurseurXY(50,22);dessinerLignePixel('             T ');
     deplacerCurseurXY(50,23);dessinerLignePixel('            T  ');
     deplacerCurseurXY(50,24);dessinerLignePixel('           T   ');
     deplacerCurseurXY(50,25);dessinerLignePixel('          T    ');
     deplacerCurseurXY(50,26);dessinerLignePixel('         T     ');
     deplacerCurseurXY(50,27);dessinerLignePixel('        TTTTTTT');
end;

end.

